[package]
name = "ed25519-zebra-ffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[build-dependencies]
cbindgen = "0.27.0"

[dependencies]
ed25519-zebra = "4.0"

[dev-dependencies]
hex-literal = "0.4.1"
